{
 "title": "CloudNativePG",
 "description": "CloudNativePG dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "PostgreSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "cnpg_backends_total{datname=~\".*\", instance=~\".*\"}",
     "legendFormat": "{{instance}} - {{datname}} - {{state}}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(cnpg_database_xact_commit_total{datname=~\".*\"}[5m])",
     "legendFormat": "{{instance}} - {{datname}} - commits"
    },
    {
     "expr": "rate(cnpg_database_xact_rollback_total{datname=~\".*\"}[5m])",
     "legendFormat": "{{instance}} - {{datname}} - rollbacks"
    }
   ]
  },
  {
   "title": "Tuples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(cnpg_database_tup_returned_total{datname=~\".*\"}[5m])",
     "legendFormat": "{{instance}} - {{datname}} - returned"
    },
    {
     "expr": "rate(cnpg_database_tup_fetched_total{datname=~\".*\"}[5m])",
     "legendFormat": "{{instance}} - {{datname}} - fetched"
    },
    {
     "expr": "rate(cnpg_database_tup_inserted_total{datname=~\".*\"}[5m])",
     "legendFormat": "{{instance}} - {{datname}} - inserted"
    },
    {
     "expr": "rate(cnpg_database_tup_updated_total{datname=~\".*\"}[5m])",
     "legendFormat": "{{instance}} - {{datname}} - updated"
    },
    {
     "expr": "rate(cnpg_database_tup_deleted_total{datname=~\".*\"}[5m])",
     "legendFormat": "{{instance}} - {{datname}} - deleted"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "cnpg_database_size_bytes{datname=~\".*\"}",
     "legendFormat": "{{instance}} - {{datname}}"
    }
   ]
  },
  { "title": "CloudNativePG", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "WAL Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "cnpg_collector_wal_count{instance=~\".*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "WAL Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "cnpg_collector_wal_size{instance=~\".*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}