apiVersion: batch/v1
kind: Job
metadata:
  name: dev-seed
  labels:
    app: dev-seed
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: dev-seed
        version: ${GIT_SHA}
    spec:
      serviceAccountName: dev-seed-sa
      initContainers:
        - name: wait-for-dependencies
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              until kubectl get pods -l app=hermione -n ${NAMESPACE} -o jsonpath='{.items[0].status.phase}' | grep -q "Running"; do
                echo "Waiting for hermione pods to be running..."
                sleep 5
              done
              until kubectl get pods -l app=mailpit -n ${NAMESPACE} -o jsonpath='{.items[0].status.phase}' | grep -q "Running"; do
                echo "Waiting for mailpit pods to be running..."
                sleep 5
              done
      containers:
        - name: dev-seed
          image: psankar/vetchi-dev-seed:${GIT_SHA}
          env:
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: uri
            - name: SERVER_URL
              value: "http://hermione:8080"
            - name: MAIL_PIT_URL
              value: "http://mailpit:8025"
      restartPolicy: Never
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-seed-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-seed-full-access-binding-devtest
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: full-access
subjects:
  - kind: ServiceAccount
    name: dev-seed-sa
    namespace: ${NAMESPACE}
