apiVersion: v1
kind: ConfigMap
metadata:
  name: granger-config
data:
  config.json: |
    {
      "env": "dev",
      "onboard_token_life": "3m",
      "port": "8080",
      "employer_base_url": "http://localhost:3001",
      "hub_base_url": "http://localhost:3002"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: granger
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: granger
  template:
    metadata:
      labels:
        app: granger
        version: ${GIT_SHA}
    spec:
      serviceAccountName: granger-sa
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - granger
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: granger
          image: vetchium/granger:${GIT_SHA}
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: uri
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: host
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: port
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: user
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-credentials
                  key: password
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: bucket
          volumeMounts:
            - name: config-volume
              mountPath: /etc/granger-config
      volumes:
        - name: config-volume
          configMap:
            name: granger-config
---
apiVersion: v1
kind: Service
metadata:
  name: granger
spec:
  selector:
    app: granger
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: granger-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: granger-full-access-binding-devtest
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: full-access
subjects:
  - kind: ServiceAccount
    name: granger-sa
    namespace: ${NAMESPACE}
