apiVersion: v1
kind: ConfigMap
metadata:
  name: hermione-config
data:
  config.json: |
    {
      "employer": {
        "web_url": "http://localhost:3001",
        "tfa_tok_life": "5m",
        "session_tok_life": "15m",
        "lts_tok_life": "730h",
        "employee_invite_tok_life": "5m"
      },
      "hub": {
        "web_url": "http://localhost:3002",
        "tfa_tok_life": "5m",
        "session_tok_life": "15m",
        "lts_tok_life": "730h",
        "hub_user_invite_tok_life": "5m",
        "password_reset_tok_life": "5m"
      },
      "port": "8080",
      "timing_attack_delay": "1s"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermione
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hermione
  template:
    metadata:
      labels:
        app: hermione
        version: ${GIT_SHA}
    spec:
      serviceAccountName: hermione-sa
      initContainers:
        - name: wait-for-sqitch
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              until kubectl get jobs -l app=sqitch -n ${NAMESPACE} -o jsonpath='{.items[-1].status.succeeded}' | grep -q '1'; do
                echo "Waiting for latest sqitch job to complete..."
                sleep 5
              done
      containers:
        - name: hermione
          image: vetchium/hermione:${GIT_SHA}
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: uri
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: access_key
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: bucket
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: endpoint
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: region
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-credentials
                  key: secret_key
          volumeMounts:
            - name: config-volume
              mountPath: /etc/hermione-config
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
      volumes:
        - name: config-volume
          configMap:
            name: hermione-config
---
apiVersion: v1
kind: Service
metadata:
  name: hermione
spec:
  selector:
    app: hermione
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hermione-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hermione-full-access-binding-devtest
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: full-access
subjects:
  - kind: ServiceAccount
    name: hermione-sa
    namespace: ${NAMESPACE}
