apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-config
data:
  API_BASE_URL: "${VETCHIUM_API_SERVER_URL}"
  MAILPIT_URL: "${MAILPIT_URL}"
  TOTAL_USERS: "${TOTAL_USERS}"
  INSTANCE_COUNT: "${TOTAL_PODS}"
  USERS_PER_INSTANCE: "${USERS_PER_POD}"
  TEST_DURATION: "${TEST_DURATION}"
  SETUP_PARALLELISM: "${SETUP_PARALLELISM}"
