# Custom values for Grafana Helm chart
# Optimized for k6 dashboards

adminPassword: "admin"

persistence:
  enabled: true
  size: 5Gi

service:
  type: LoadBalancer
  port: 80

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server:9090
      access: proxy
      isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'k6'
      orgId: 1
      folder: 'k6'
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/k6

dashboardsConfigMaps:
  k6: "k6-dashboards"

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi
