# Custom values for Prometheus Helm chart
# Optimized for k6 metrics collection

server:
  persistentVolume:
    enabled: true
    size: 8Gi
  
  # Enable remote write API for k6 to push metrics
  remoteWrite:
    - url: "http://localhost:9090/api/v1/write"
      writeRelabelConfigs:
        - sourceLabels: [__name__]
          regex: "k6_.*"
          action: keep
  
  # Configure retention settings
  retention: 15d
  retentionSize: 6GB

  # Resources for Prometheus server
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

  # Expose Prometheus server as a LoadBalancer for k6 access
  service:
    type: LoadBalancer
    port: 9090

alertmanager:
  enabled: false  # Not needed for k6 testing

pushgateway:
  enabled: false  # Not needed for k6 testing

# Disable unnecessary components
kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false
