FROM node:20-alpine AS builder

WORKDIR /app

COPY typespec/ typespec/
WORKDIR /app/ronweasly
COPY ronweasly/package*.json ./
RUN npm ci
COPY ronweasly/ .
RUN npm run build

FROM node:20-alpine

WORKDIR /app
COPY --from=builder /app/ronweasly/.next ./.next
COPY --from=builder /app/ronweasly/public ./public
COPY --from=builder /app/ronweasly/package*.json ./
COPY --from=builder /app/ronweasly/next.config.js ./

RUN npm ci --production

ENV PORT=3001
EXPOSE 3001

CMD ["npm", "start"] 