{{- if .Values.devSeed.enabled }}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "vetchium-apps-helm.fullname" . }}-dev-seed
  labels:
    {{- include "vetchium-apps-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: dev-seed
spec:
  backoffLimit: {{ .Values.devSeed.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "vetchium-apps-helm.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: dev-seed
        # Use explicit tag if provided, otherwise chart version
        version: {{ default .Chart.AppVersion .Values.devSeed.image.tag }}
    spec:
      {{- if .Values.devSeed.serviceAccount.create }}
      serviceAccountName: {{ include "vetchium-apps-helm.devSeedServiceAccountName" . }}
      {{- else if .Values.devSeed.serviceAccount.name }}
      serviceAccountName: {{ .Values.devSeed.serviceAccount.name }}
      {{- end }}
      initContainers:
        - name: wait-for-dependencies
          image: {{ .Values.devSeed.initContainer.kubectlImage }}
          command:
            - /bin/sh
            - -c
            - |
              HERMIONE_SELECTOR="app.kubernetes.io/instance={{ .Release.Name }},{{ .Values.devSeed.initContainer.hermioneComponentLabel }}"
              MAILPIT_SELECTOR="{{ .Values.devSeed.initContainer.mailpitLabelSelector }}"
              POSTGRES_SELECTOR="{{ .Values.devSeed.initContainer.postgresLabelSelector }}"

              until kubectl get pods -l "${POSTGRES_SELECTOR}" -n {{ .Release.Namespace }} -o jsonpath='{.items[*].status.conditions[?(@.type=="Ready")].status}' | grep -q "True"; do
                echo "Waiting for PostgreSQL pods (${POSTGRES_SELECTOR}) to be ready..."
                sleep 5
              done

              until kubectl get pods -l "${HERMIONE_SELECTOR}" -n {{ .Release.Namespace }} -o jsonpath='{.items[0].status.phase}' | grep -q "Running"; do
                echo "Waiting for hermione pods (${HERMIONE_SELECTOR}) to be running..."
                sleep 5
              done

              until kubectl get pods -l "${MAILPIT_SELECTOR}" -n {{ .Release.Namespace }} -o jsonpath='{.items[0].status.phase}' | grep -q "Running"; do
                echo "Waiting for mailpit pods (${MAILPIT_SELECTOR}) to be running..."
                sleep 5
              done
      containers:
        - name: dev-seed
          image: "{{ .Values.devSeed.image.repository }}:{{ default .Chart.AppVersion .Values.devSeed.image.tag }}"
          imagePullPolicy: {{ .Values.devSeed.image.pullPolicy }}
          env:
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.devSeed.secrets.postgres }} # Assumes secret is in the same namespace
                  key: uri
            - name: SERVER_URL
              value: {{ .Values.devSeed.hermioneServiceUrl | quote }}
            - name: MAIL_PIT_URL
              value: {{ .Values.devSeed.mailpitServiceUrl | quote }}
          # Add resource limits/requests if needed
          # resources:
      restartPolicy: Never

---

{{- if .Values.devSeed.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vetchium-apps-helm.devSeedServiceAccountName" . }}
  labels:
    {{- include "vetchium-apps-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: dev-seed
  {{- with .Values.devSeed.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

---

{{- if .Values.devSeed.clusterRoleBinding.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vetchium-apps-helm.fullname" . }}-dev-seed-crb
  labels:
    {{- include "vetchium-apps-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: dev-seed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.devSeed.clusterRoleBinding.clusterRoleName }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vetchium-apps-helm.devSeedServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}

{{- end }}