apiVersion: v1
kind: ConfigMap
metadata:
  name: granger-config
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/name: {{ .Chart.Name | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: granger
data:
  config.json: |
    {
      "env": {{ .Values.granger.config.env | quote }},
      "onboard_token_life": {{ .Values.granger.config.onboardTokenLife | quote }},
      "port": {{ .Values.granger.config.port | quote }},
      "employer_base_url": {{ .Values.granger.config.employerBaseUrl | quote }},
      "hub_base_url": {{ .Values.granger.config.hubBaseUrl | quote }}
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: granger
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/name: {{ .Chart.Name | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: granger
spec:
  replicas: {{ .Values.granger.replicaCount }}
  strategy:
    type: {{ .Values.granger.strategy }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name | trunc 63 | trimSuffix "-" }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: granger
  template:
    metadata:
      {{- with .Values.granger.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ .Chart.Name | trunc 63 | trimSuffix "-" }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: granger
    spec:
      {{- with .Values.granger.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ if .Values.granger.serviceAccount.create }}{{ printf "%s-granger-sa" .Release.Name }}{{ else }}{{ default "default" .Values.granger.serviceAccount.name }}{{ end }}
      securityContext:
        {{- with .Values.granger.podSecurityContext }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.granger.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: granger
          securityContext:
            {{- with .Values.granger.securityContext }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          image: "{{ .Values.granger.image.repository }}:{{ .Values.granger.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.granger.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.granger.config.port | int }} # Use the port from config
              protocol: TCP
          env:
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.granger.secrets.postgres }}
                  key: uri
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.granger.secrets.smtp }}
                  key: host
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.granger.secrets.smtp }}
                  key: port
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.granger.secrets.smtp }}
                  key: user
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.granger.secrets.smtp }}
                  key: password
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.granger.secrets.s3 }}
                  key: bucket
          # Add livenessProbe, readinessProbe if needed
          resources:
            {{- with .Values.granger.resources }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/granger-config
      volumes:
        - name: config-volume
          configMap:
            name: granger-config # Reference the templated ConfigMap name
      {{- with .Values.granger.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.granger.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: granger
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/name: {{ .Chart.Name | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: granger
spec:
  type: {{ .Values.granger.service.type }}
  ports:
    - port: {{ .Values.granger.service.port }}
      targetPort: http # Reference container port name
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: granger
---
{{- if .Values.granger.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-granger-sa" (default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-")) .Values.granger.serviceAccount.name | trunc 63 | trimSuffix "-" }}
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: granger
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.grangerClusterRoleBinding.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: granger-access-binding
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: granger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.grangerClusterRoleBinding.clusterRoleName }}
subjects:
  - kind: ServiceAccount
    name: {{ default (printf "%s-granger-sa" (default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-")) .Values.granger.serviceAccount.name | trunc 63 | trimSuffix "-" }}
    namespace: {{ .Release.Namespace }}
{{- end }}
