apiVersion: v1
kind: ConfigMap
metadata:
  name: granger-config
data:
  config.json: |
    {
      "env": {{ .Values.granger.config.env | quote }},
      "onboard_token_life": {{ .Values.granger.config.onboardTokenLife | quote }},
      "port": {{ .Values.granger.config.port | quote }},
      "employer_base_url": {{ .Values.granger.config.employerBaseUrl | quote }},
      "hub_base_url": {{ .Values.granger.config.hubBaseUrl | quote }}
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: granger
spec:
  replicas: {{ .Values.granger.replicaCount }}
  strategy:
    type: {{ .Values.granger.strategy }}
  selector:
    matchLabels:
      app: granger
  template:
    metadata:
      labels:
        app: granger
        version: {{ .Values.granger.image.tag | default .Values.global.imageTag }}
    spec:
      serviceAccountName: {{ .Release.Name }}-granger-sa
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - granger
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: granger
          image: "{{ .Values.granger.image.repository }}:{{ .Values.granger.image.tag | default .Values.global.imageTag }}"
          ports:
            - containerPort: {{ .Values.granger.config.port | int }}
          env:
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.granger.secrets.postgres }}
                  key: uri
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.granger.secrets.smtp }}
                  key: host
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.granger.secrets.smtp }}
                  key: port
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.granger.secrets.smtp }}
                  key: user
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.granger.secrets.smtp }}
                  key: password
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.granger.secrets.s3 }}
                  key: bucket
          volumeMounts:
            - name: config-volume
              mountPath: /etc/granger-config
      volumes:
        - name: config-volume
          configMap:
            name: granger-config
---
apiVersion: v1
kind: Service
metadata:
  name: granger
spec:
  selector:
    app: granger
  ports:
    - protocol: TCP
      port: {{ .Values.granger.service.port }}
      targetPort: {{ .Values.granger.config.port | int }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-granger-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-granger-access-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: full-access
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-granger-sa
    namespace: {{ .Release.Namespace }}
