apiVersion: apps/v1
kind: Deployment
metadata:
  name: harrypotter
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/name: {{ .Chart.Name | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: harrypotter
spec:
  replicas: {{ .Values.harrypotter.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name | trunc 63 | trimSuffix "-" }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: harrypotter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name | trunc 63 | trimSuffix "-" }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: harrypotter
    spec:
      serviceAccountName: default
      containers:
        - name: harrypotter
          image: "{{ .Values.harrypotter.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.harrypotter.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.harrypotter.service.targetPort }}
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: harrypotter
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/name: {{ .Chart.Name | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: harrypotter
spec:
  type: {{ .Values.harrypotter.service.type }}
  ports:
    - port: {{ .Values.harrypotter.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: harrypotter
