apiVersion: apps/v1
kind: Deployment
metadata:
  name: harrypotter
spec:
  selector:
    matchLabels:
      app: harrypotter
  template:
    metadata:
      labels:
        app: harrypotter
        version: {{ .Values.harrypotter.image.tag }}
    spec:
      containers:
        - name: harrypotter
          image: "{{ .Values.harrypotter.image.repository }}:{{ .Values.harrypotter.image.tag }}"
          ports:
            - containerPort: {{ .Values.harrypotter.service.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: harrypotter
spec:
  type: {{ .Values.harrypotter.service.type }}
  selector:
    app: harrypotter
  ports:
    - protocol: TCP
      port: {{ .Values.harrypotter.service.port }}
      targetPort: {{ .Values.harrypotter.service.targetPort }}
