apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  annotations:
    # This annotation tells the webhook to use the service in the vetchium-devtest-env namespace
    postgresql.cnpg.io/webhook-url: "https://cnpg-webhook-service.vetchium-devtest-env.svc:443/validate"
spec:
  instances: 1
  storage:
    size: 10Gi
  monitoring:
    enablePodMonitor: true
  inheritedMetadata:
    labels:
      app: postgres
  backup:
    barmanObjectStore:
      # db-backups below is the bucket name
      destinationPath: "s3://db-backups/barman"
      endpointURL: "http://minio:9000"
      s3Credentials:
        accessKeyId:
          name: s3-credentials
          key: access_key
        secretAccessKey:
          name: s3-credentials
          key: secret_key
