apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 3
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
  inheritedMetadata:
    labels:
      app: postgres
  backup:
    barmanObjectStore:
      # db-backups below is the bucket name
      destinationPath: "s3://db-backups/barman"
      endpointURL: "http://minio:9000"
      s3Credentials:
        accessKeyId:
          name: s3-credentials
          key: access_key
        secretAccessKey:
          name: s3-credentials
          key: secret_key
