apiVersion: apps/v1
kind: Deployment
metadata:
  name: ronweasly
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/name: {{ .Chart.Name | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: ronweasly
spec:
  replicas: {{ .Values.ronweasly.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name | trunc 63 | trimSuffix "-" }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: ronweasly
  template:
    metadata:
      {{- with .Values.ronweasly.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: {{ .Chart.Name | trunc 63 | trimSuffix "-" }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: ronweasly
    spec:
      {{- with .Values.ronweasly.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ default "default" .Values.ronweasly.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.ronweasly.podSecurityContext | nindent 8 }}
      containers:
        - name: ronweasly
          securityContext:
            {{- toYaml .Values.ronweasly.securityContext | nindent 12 }}
          image: "{{ .Values.ronweasly.image.repository }}:{{ .Values.ronweasly.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ronweasly.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ronweasly.service.targetPort }}
              protocol: TCP
          {{- with .Values.ronweasly.livenessProbe }}
          livenessProbe:
            httpGet:
              path: {{ .httpGet.path }}
              port: http # references the containerPort name 'http'
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            {{- if .timeoutSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            {{- end }}
            {{- if .failureThreshold }}
            failureThreshold: {{ .failureThreshold }}
            {{- end }}
            {{- if .successThreshold }}
            successThreshold: {{ .successThreshold }}
            {{- end }}
          {{- end }}
          {{- with .Values.ronweasly.readinessProbe }}
          readinessProbe:
            httpGet:
              path: {{ .httpGet.path }}
              port: http # references the containerPort name 'http'
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            {{- if .timeoutSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            {{- end }}
            {{- if .failureThreshold }}
            failureThreshold: {{ .failureThreshold }}
            {{- end }}
            {{- if .successThreshold }}
            successThreshold: {{ .successThreshold }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.ronweasly.resources | nindent 12 }}
      {{- with .Values.ronweasly.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ronweasly.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ronweasly.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: ronweasly
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: ronweasly
spec:
  type: {{ .Values.ronweasly.service.type }}
  ports:
    - port: {{ .Values.ronweasly.service.port }}
      targetPort: http # references the containerPort name 'http'
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ronweasly
