apiVersion: apps/v1
kind: Deployment
metadata:
  name: ronweasly
spec:
  selector:
    matchLabels:
      app: ronweasly
  template:
    metadata:
      labels:
        app: ronweasly
        version: {{ .Values.ronweasly.image.tag | default .Values.global.imageTag }}
    spec:
      containers:
        - name: ronweasly
          image: "{{ .Values.ronweasly.image.repository }}:{{ .Values.ronweasly.image.tag | default .Values.global.imageTag }}"
          ports:
            - containerPort: {{ .Values.ronweasly.service.targetPort }}
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.ronweasly.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.ronweasly.service.targetPort }}
            initialDelaySeconds: 15
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: ronweasly
spec:
  type: {{ .Values.ronweasly.service.type }}
  selector:
    app: ronweasly
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.ronweasly.service.port }}
      targetPort: {{ .Values.ronweasly.service.targetPort }}
