apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vetchium-apps-helm.fullname" . }}-sortinghat-config
  labels:
    {{- include "vetchium-apps-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: sortinghat
data:
  config.json: |
    {
      "port": {{ .Values.sortinghat.config.port | quote }}
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vetchium-apps-helm.fullname" . }}-sortinghat
  labels:
    {{- include "vetchium-apps-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: sortinghat
spec:
  replicas: {{ .Values.sortinghat.replicaCount }}
  selector:
    matchLabels:
      {{- include "vetchium-apps-helm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: sortinghat
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vetchium-apps-helm.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: sortinghat
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vetchium-apps-helm.sortinghatServiceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: sortinghat
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.sortinghat.image.repository }}:{{ .Values.sortinghat.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.sortinghat.image.pullPolicy }}
          ports:
            - name: http # Name the port for probe referencing
              containerPort: {{ .Values.sortinghat.config.port | int }}
              protocol: TCP
          env:
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sortinghat.secrets.s3 }}
                  key: endpoint
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sortinghat.secrets.s3 }}
                  key: access_key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sortinghat.secrets.s3 }}
                  key: secret_key
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sortinghat.secrets.s3 }}
                  key: region
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sortinghat.secrets.s3 }}
                  key: bucket
          volumeMounts:
            - name: config-volume
              mountPath: /etc/sortinghat-config
          {{- with .Values.sortinghat.livenessProbe }}
          livenessProbe:
            httpGet:
              path: {{ .httpGet.path }}
              port: http # Reference container port name
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            {{- if .timeoutSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            {{- end }}
            {{- if .failureThreshold }}
            failureThreshold: {{ .failureThreshold }}
            {{- end }}
            {{- if .successThreshold }}
            successThreshold: {{ .successThreshold }}
            {{- end }}
          {{- end }}
          {{- with .Values.sortinghat.readinessProbe }}
          readinessProbe:
            httpGet:
              path: {{ .httpGet.path }}
              port: http # Reference container port name
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            {{- if .timeoutSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            {{- end }}
            {{- if .failureThreshold }}
            failureThreshold: {{ .failureThreshold }}
            {{- end }}
            {{- if .successThreshold }}
            successThreshold: {{ .successThreshold }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.sortinghat.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "vetchium-apps-helm.fullname" . }}-sortinghat-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vetchium-apps-helm.fullname" . }}-sortinghat
  labels:
    {{- include "vetchium-apps-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: sortinghat
spec:
  type: {{ .Values.sortinghat.service.type }}
  ports:
    - port: {{ .Values.sortinghat.service.port }}
      targetPort: {{ .Values.sortinghat.service.targetPort }} # Use explicit targetPort from values
      protocol: TCP
      name: http
  selector:
    {{- include "vetchium-apps-helm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: sortinghat
---
{{- if .Values.sortinghat.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vetchium-apps-helm.sortinghatServiceAccountName" . }}
  labels:
    {{- include "vetchium-apps-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: sortinghat
  {{- with .Values.sortinghat.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.sortinghat.clusterRoleBinding.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vetchium-apps-helm.fullname" . }}-sortinghat-access-binding
  labels:
    {{- include "vetchium-apps-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: sortinghat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.sortinghat.clusterRoleBinding.clusterRoleName }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vetchium-apps-helm.sortinghatServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
