apiVersion: batch/v1
kind: Job
metadata:
  name: sqitch-{{ .Values.sqitch.image.tag }}
  labels:
    app: sqitch
spec:
  backoffLimit: 5
  template:
    metadata:
      labels:
        app: sqitch
        version: {{ .Values.sqitch.image.tag }}
    spec:
      serviceAccountName: sqitch-sa
      initContainers:
        - name: wait-for-postgres
          image: bitnami/kubectl:latest
          command: ["sh", "-c"]
          args:
            - |
              until kubectl get pods -l app=postgres -n {{ .Release.Namespace }} -o jsonpath='{.items[*].status.conditions[?(@.type=="Ready")].status}' | grep -q "True"; do
                echo "Waiting for PostgreSQL to be ready..."
                sleep 5
              done
      containers:
        - name: sqitch
          image: "{{ .Values.sqitch.image.repository }}:{{ .Values.sqitch.image.tag }}"
          imagePullPolicy: {{ .Values.sqitch.image.pullPolicy }}
          command: ["sh", "-c"]
          args:
            - |
              set -e
              # Transform postgresql:// to db:pg:// format expected by sqitch
              URI=$(cat /mnt/secrets/uri | sed 's|postgresql://|db:pg://|')
              echo "Deploying Sqitch changes..."
              sqitch deploy --verbose "${URI}"
              echo "Verifying Sqitch changes..."
              sqitch verify --verbose "${URI}"
              echo "Sqitch deployment complete."
          volumeMounts:
            - name: postgres-creds
              mountPath: /mnt/secrets
              readOnly: true
          # Add resource limits/requests if needed
          # resources:
      volumes:
        - name: postgres-creds
          secret:
            secretName: {{ .Values.sqitch.secrets.postgres }} # Assumes secret is in the same namespace
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: vetchium-tags-creat-{{ .Values.sqitch.image.tag }}
  labels:
    app: vetchium-tags-creat
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: vetchium-tags-creat
        version: {{ .Values.sqitch.image.tag }}
    spec:
      serviceAccountName: sqitch-sa
      initContainers:
        - name: wait-for-sqitch
          image: bitnami/kubectl:latest
          command: ["sh", "-c"]
          args:
            - |
              echo "Waiting for sqitch job to complete..."
              until kubectl wait --for=condition=complete job/sqitch-{{ .Values.sqitch.image.tag }} --timeout=600s -n {{ .Release.Namespace }}; do
                echo "Sqitch job not complete yet, waiting..."
                sleep 10
              done
              echo "Sqitch job completed successfully"
      containers:
        - name: vetchium-tags-creat
          image: "{{ .Values.sqitch.image.repository }}:{{ .Values.sqitch.image.tag }}"
          imagePullPolicy: {{ .Values.sqitch.image.pullPolicy }}
          command: ["sh", "-c"]
          args:
            - |
              set -e
              echo "Starting vetchium-tags-creat job..."
              
              # Get the PostgreSQL connection URI (no transformation needed for psql)
              URI=$(cat /mnt/secrets/uri)
              echo "Connecting to database..."
              
              # Read and process the JSON file to insert tags
              echo "Processing vetchium-tags.json..."
              cat /vetchi/migrations/vetchium-tags.json | jq -r '.[] | "INSERT INTO tags (id, display_name) VALUES (\047" + .id + "\047, \047" + .display_name + "\047) ON CONFLICT (id) DO NOTHING;"' | psql "${URI}"
              
              echo "Tags insertion completed successfully"
          volumeMounts:
            - name: postgres-creds
              mountPath: /mnt/secrets
              readOnly: true
      volumes:
        - name: postgres-creds
          secret:
            secretName: {{ .Values.sqitch.secrets.postgres }}
      restartPolicy: Never
---
{{- if .Values.sqitch.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sqitch-sa
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: sqitch
  {{- with .Values.sqitch.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- if .Values.sqitch.clusterRoleBinding.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-sqitch-crb
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/name: {{ default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: sqitch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.sqitch.clusterRoleBinding.clusterRoleName }}
subjects:
  - kind: ServiceAccount
    name: sqitch-sa
    namespace: {{ .Release.Namespace }}
{{- end }}
