# Global configuration
global:
  vmaddr: "localhost" # This will be overridden by helm install/upgrade --set global.vmaddr=<actual_vmaddr>
  imageTag: "latest" # This will be overridden by helm install/upgrade --set global.imageTag=<git_sha>

# Dependencies
minio:
  fullnameOverride: minio
  mode: standalone
  accessKey:
    password: "minioadmin"
  secretKey:
    password: "minioadmin"

mailpit:
  fullnameOverride: mailpit
  service:
    http:
      type: LoadBalancer
      port: 8025

# Specific application configurations
harrypotter:
  replicaCount: 1
  image:
    repository: ghcr.io/vetchium/harrypotter
    pullPolicy: IfNotPresent
    tag: "{{ .Values.global.imageTag }}"
  service:
    type: LoadBalancer
    port: 3001
    targetPort: 3000

granger:
  replicaCount: 1
  strategy: Recreate
  image:
    repository: ghcr.io/vetchium/granger
    pullPolicy: IfNotPresent
    tag: "{{ .Values.global.imageTag }}"
  serviceAccount:
    create: true
  config:
    env: "dev"
    onboardTokenLife: "3m"
    port: "8080"
    employerBaseUrl: "http://localhost:3001"
    hubBaseUrl: "http://localhost:3002"
  secrets:
    postgres: postgres-app
    smtp: smtp-credentials
    s3: s3-credentials
  service:
    type: ClusterIP
    port: 8080

hermione:
  replicaCount: 3
  image:
    repository: ghcr.io/vetchium/hermione
    pullPolicy: IfNotPresent
    tag: "{{ .Values.global.imageTag }}"
  serviceAccount:
    create: true
  initContainer:
    enabled: true
    kubectlImage: bitnami/kubectl:latest
    sqitchJobLabelSelector: "app.kubernetes.io/component=sqitch"
  config:
    employerWebUrl: "http://localhost:3001"
    employerTfaTokLife: "5m"
    employerSessionTokLife: "15m"
    employerLtsTokLife: "730h"
    employerEmployeeInviteTokLife: "5m"
    hubWebUrl: "http://localhost:3002"
    hubTfaTokLife: "5m"
    hubSessionTokLife: "15m"
    hubLtsTokLife: "730h"
    hubUserInviteTokLife: "5m"
    passwordResetTokLife: "5m"
    port: "8080"
    timingAttackDelay: "1s"
  secrets:
    postgres: postgres-app
    s3: s3-credentials
  service:
    type: LoadBalancer
    port: 8080
    targetPort: 8080
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi

ronweasly:
  replicaCount: 1
  image:
    repository: ghcr.io/vetchium/ronweasly
    pullPolicy: IfNotPresent
    tag: "{{ .Values.global.imageTag }}"
  serviceAccount:
    create: false
    name: "default"
  service:
    type: LoadBalancer
    port: 3002
    targetPort: 3000
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  readinessProbe:
    httpGet:
      path: /
    initialDelaySeconds: 10
    periodSeconds: 5
  livenessProbe:
    httpGet:
      path: /
    initialDelaySeconds: 15
    periodSeconds: 10

sortinghat:
  replicaCount: 1
  image:
    repository: ghcr.io/vetchium/sortinghat
    pullPolicy: IfNotPresent
    tag: "{{ .Values.global.imageTag }}"
  config:
    port: "8080"
  serviceAccount:
    create: true
  secrets:
    s3: s3-credentials
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "3Gi"
      cpu: "3"
  livenessProbe:
    httpGet:
      path: /health
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /health
    initialDelaySeconds: 5
    periodSeconds: 5
  clusterRoleBinding:
    create: true
    clusterRoleName: full-access

sqitch:
  enabled: true
  backoffLimit: 5
  image:
    repository: ghcr.io/vetchium/sqitch
    pullPolicy: IfNotPresent
    tag: "{{ .Values.global.imageTag }}"
  serviceAccount:
    create: true
  secrets:
    postgres: postgres-app
  initContainer:
    kubectlImage: bitnami/kubectl:latest
    postgresLabelSelector: "cnpg.io/cluster=postgres"
  clusterRoleBinding:
    create: true
    clusterRoleName: full-access

devSeed:
  enabled: true
  backoffLimit: 3
  image:
    repository: ghcr.io/vetchium/dev-seed
    pullPolicy: IfNotPresent
    tag: "{{ .Values.global.imageTag }}"
  serviceAccount:
    create: true
  secrets:
    postgres: postgres-app
  hermioneServiceUrl: "http://hermione:{{ .Values.hermione.service.port }}"
  mailpitPort: 8025
  initContainer:
    kubectlImage: bitnami/kubectl:latest
    postgresLabelSelector: "cnpg.io/cluster=postgres"
    hermioneComponentLabel: "app.kubernetes.io/component=hermione"
    mailpitLabelSelector: "app.kubernetes.io/name=mailpit"
  clusterRoleBinding:
    create: true
    clusterRoleName: full-access
