//go:build ignore
// +build ignore

package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"text/template"
	"time"
)

const timezonesJSONPath = "timezones.json"
const templateFileTimezones = `// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// {{ .Timestamp }}

package common

func init() {
	validTimezones = map[string]struct{}{
{{range .Timezones}}		"{{.Name}}": {},
{{end}}	}
}`

type TimezoneEntry struct {
	Name     string `json:"name"`
	Obsolete bool   `json:"obsolete"`
}

func main() {
	jsonData, err := os.ReadFile(timezonesJSONPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading timezones.json: %v\n", err)
		os.Exit(1)
	}

	var timezones []TimezoneEntry
	if err := json.Unmarshal(jsonData, &timezones); err != nil {
		fmt.Fprintf(os.Stderr, "Error unmarshalling timezones.json: %v\n", err)
		os.Exit(1)
	}

	var validTimezones []TimezoneEntry
	for _, tz := range timezones {
		if !tz.Obsolete {
			validTimezones = append(validTimezones, tz)
		} else {
			fmt.Printf("Skipping obsolete timezone: %s\n", tz.Name)
		}
	}

	templ := template.Must(
		template.New("timezones").Parse(templateFileTimezones),
	)

	data := struct {
		Timestamp string
		Timezones []TimezoneEntry
	}{
		Timestamp: time.Now().Format(time.RFC1123),
		Timezones: validTimezones,
	}

	var generatedCode bytes.Buffer
	if err := templ.Execute(&generatedCode, data); err != nil {
		fmt.Fprintf(os.Stderr, "Error executing timezone template: %v\n", err)
		os.Exit(1)
	}

	formattedCode, err := format.Source(generatedCode.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error formatting generated tz code: %v\n", err)
		os.Exit(1)
	}

	err = os.WriteFile("generated_timezone_codes.go", formattedCode, 0644)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error writing generated tz codes: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("Successfully generated generated_timezone_codes.go")
}
