# vetchium-env-helm/Chart.yaml
apiVersion: v2
name: vetchium-env-helm
description: A Helm chart for Vetchium environment that installs CloudNativePG, Prometheus, Grafana, MinIO, and Mailpit
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: cloudnative-pg
    version: "0.23.2"
    repository: "https://cloudnative-pg.github.io/charts"
  - name: kube-prometheus-stack
    version: "71.0.0"
    repository: "https://prometheus-community.github.io/helm-charts"
  - name: minio
    version: "5.0.11"
    repository: "https://charts.min.io/"
  - name: mailpit
    version: "0.24.0"
    repository: "https://jouve.github.io/charts"
