FROM --platform=$BUILDPLATFORM golang:1.24.4-bullseye AS builder
ARG TARGETARCH
ARG TARGETOS
WORKDIR /app
COPY api/go.mod api/go.sum ./
# For production builds, remove the replace directive
RUN test -d typespec || go mod edit -dropreplace github.com/vetchium/vetchium/typespec
RUN go mod download
COPY api/ .
COPY typespec/ ../typespec/

# Generate code for typespec/common
RUN cd ../typespec/common && go generate ./...

RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -o hermione ./cmd/hermione

# build a minimal container
FROM --platform=$TARGETPLATFORM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/internal/hedwig/templates ./hedwig/templates
COPY --from=builder /app/hermione .
CMD ["./hermione"]
