FROM golang:1.23.2 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o granger ./cmd/granger

# build a minimal container
FROM gcr.io/distroless/base-debian10
WORKDIR /app
COPY --from=builder /app/granger .
CMD ["./granger"]
