FROM --platform=$BUILDPLATFORM golang:1.24.1-bullseye AS builder
ARG TARGETARCH
ARG TARGETOS
WORKDIR /app
COPY api/go.mod api/go.sum ./
RUN test -d typespec || go mod edit -dropreplace github.com/psankar/vetchi/typespec
RUN go mod download
COPY api/ .
COPY typespec/ ../typespec/
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -o granger ./cmd/granger

# build a minimal container
FROM --platform=$TARGETPLATFORM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/granger .
CMD ["./granger"]
