FROM golang:1.23.2-bullseye AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o hermione ./cmd/hermione

# build a minimal container
FROM gcr.io/distroless/base-debian10
WORKDIR /app
COPY --from=builder /app/hermione .
CMD ["./hermione"]
