FROM golang:1.24.1-bullseye AS builder
WORKDIR /app
COPY api/go.mod api/go.sum ./
RUN test -d typespec || go mod edit -dropreplace github.com/psankar/vetchi/typespec
RUN go mod download
COPY api/ .
COPY typespec/ ../typespec/
RUN go build -o granger ./cmd/granger

# build a minimal container
FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/granger .
CMD ["./granger"]
